### ISSUE TITLE
misaka 2.0.0. does not have all constants

### ISSUE THREAD

**Issue by FvD** [singingwolfboy/flask-misaka#11]
When trying to run flask-misaka==0.3 with misaka==2.0.0. errors with the import of constants show up. Apparently not all imported constants are available in misaka==2.0.0. For example:

    Traceback (most recent call last):
      Python Shell, prompt 5, line 1
    builtins.ImportError: cannot import name 'EXT_LAX_HTML_BLOCKS'

Downgrading misaka to 1.0.2 solves these issues.

**Comment by nickw444** [comment]
+1

**Comment by singingwolfboy** [comment]
Flask-Misaka is currently incompatible with misaka 2.0, as noted in the `setup.py` file. (https://github.com/singingwolfboy/flask-misaka/commit/53a42a23df1e503cb5b5fa219d57354ce05fd7a4) At some point, I'll get around to updating Flask-Misaka to work with misaka 2.0.

**Comment by nickw444** [comment]
That commit isn't on PyPi (last PyPi version was uploaded on 2014-04-22). It's probably worth hotfixing that single commit if there are other changes not yet approved for production.

In the mean time, for others stumbling across this page, just add: 
```
misaka<2.0
```
to your requirements file.

**Comment by flamusdiu** [comment]
Should be fixed by #12 when I finish the docs

**Comment by singingwolfboy** [comment]
I've finished up the docs, tagged a new release, and uploaded it to PyPI. Please test it out!

**Comment by flamusdiu** [comment]
@singingwolfboy thanks ... sorry I got sidetracked with holiday stuff.
